#!/bin/sh -e
# Simple wrapper for /etc/init.d/sneakers-* scripts

application=$1
directory=$2
pid_file=$3
environment=$4

cd $directory

# Find bundle in application bin or script directory (which should select the perfect ruby version)
export PATH=$PWD/bin:$PWD/script:$PATH
export RAILS_ENV=$environment
export PID_FILE=$pid_file
bundle exec rails sneakers:work 2>&1 | logger -t "sneakers/$application"
