#!/bin/sh

base_dir=$1

directories="$base_dir/releases/ $base_dir/shared/bundle $base_dir/shared/assets $base_dir/shared/cached-copy $base_dir/repo $base_dir/shared/public/assets"

find $directories -type d -print0 | xargs -0 chmod g+ws
find $directories -print0 | xargs -0 chmod g+w

chgrp -R src $directories

exit 0
