#!/bin/sh

base_dir=$1

find $base_dir/releases/ $base_dir/shared/bundle -type d -print0 | xargs -0 sudo chmod g+ws
find $base_dir/releases/ $base_dir/shared/bundle -print0 | xargs -0 sudo chmod g+w 

exit 0
