#!/bin/sh -e
# Simple wrapper for /etc/init.d/sidekiq-* scripts

application=$1
directory=$2
pid_file=$3
environment=$4

cd $directory

# Find bundle in application bin or script directory (which should select the perfect ruby version)
export PATH=$PWD/bin:$PWD/script:$PATH

bundle exec sidekiq -e $environment -P $pid_file 2>&1 | logger -t "sidekiq/$application"
